project:
  type: website
  output-dir: _site

website:
  title: "Nombre de Tu Curso"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Lecciones"
        href: lecciones.qmd

format:
  html:
    theme: cosmo
    toc: true
    lang: es
